"""empty message

Revision ID: 88334a66efca
Revises:
Create Date: 2022-08-02 10:32:18.467658

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '88334a66efca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=30), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=30), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('birthday', sa.Date(), nullable=False),
                    sa.Column('bio', sa.String(length=101), nullable=True),
                    sa.Column('lives_in', sa.String(
                        length=255), nullable=True),
                    sa.Column('born_from', sa.String(
                        length=255), nullable=True),
                    sa.Column('profile_pic', sa.String(
                        length=255), nullable=True),
                    sa.Column('cover_pic', sa.String(
                        length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('friends',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('friend_id', sa.Integer(), nullable=False),
                    sa.Column('accepted', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['friend_id'], ['users.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=30), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('image_link', sa.String(
                        length=255), nullable=False),
                    sa.Column('created_at', sa.String(
                        length=255), nullable=False),
                    sa.Column('edited_at', sa.String(
                        length=255), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.String(
                        length=255), nullable=False),
                    sa.Column('edited_at', sa.String(
                        length=255), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

        op.execute(f"ALTER TABLE friends SET SCHEMA {SCHEMA};")

        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")

        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
